package by.htp.ts.command;

public enum CommandName {
	AUTHORIZATION, REGISTRATION, LOGOUT,
	
	GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE,
	GO_TO_MAIN_PAGE, GO_TO_ERROR_PAGE,
	CHANGE_LANGUAGE
}
